let ONE_SECOND = 1000;
let FIVE_SECONDS = 5 * ONE_SECOND;
let TEN_SECONDS = 10 * ONE_SECOND;
let THIRTY_SECONDS = 30 * ONE_SECOND;
let ONE_MINUTE = 60 * ONE_SECOND;
let FIVE_MINUTES = 5 * ONE_MINUTE;
let TEN_MINUTES = 10 * ONE_MINUTE;

export default Object.freeze({
    ONE_SECOND,
    FIVE_SECONDS,
    TEN_SECONDS,
    THIRTY_SECONDS,
    ONE_MINUTE,
    FIVE_MINUTES,
    TEN_MINUTES
})